### ISSUE TITLE
Add new hat block "when this sprite touches"

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#1532]
There's already code in the VM to support this new hat block, but adding it will require resolving these issues:

- [ ] https://github.com/LLK/scratch-gui/issues/2301 Should we re-trigger the "When Touching" hat while it's running?
- [ ] https://github.com/LLK/scratch-vm/issues/1220 "when touching" hat gets "stuck on" when used with clones
- [ ] https://github.com/LLK/scratch-gui/issues/2300 Touching Edge reporter and Hat blocks don't report if If On Edge Bounce block is running
