### ISSUE TITLE
Extensionification: All blocks should be implemented using extension system

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-vm#2120]
# Extensionification!

## Goals

- All blocks in Scratch 3.0 should be entirely defined within `scratch-vm`. Adding a new block should not require modifications in `scratch-gui` or `scratch-blocks`.
- All blocks in Scratch 3.0 should be implemented in the same way. We should not maintain two (or more) different ways to define blocks.
- The extension system should be enhanced such that it becomes powerful enough to implement every existing Scratch 3.0 block.

## Tasks

* Supporting features
  * [x] Extensions should be able to place buttons in the toolbox
  * [ ] Extension blocks should refresh when changing targets
  * [ ] Extension blocks should refresh on certain actions (create/update/delete variable, list, procedure, message, etc.)
  * [ ] Extensionified categories can be interleaved with categories defined in `scratch-gui`'s `makeToolboxXML`
* Serialization
  * [ ] Existing SB3 files, including those containing variables, lists, or custom procedures, can be loaded correctly when those categories are extensionified.
  * [ ] An SB3 file saved with extensionified variables, lists, or custom procedures can be loaded correctly in an older editor (esp. Scratch Desktop).
* Categories
  * [ ] Motion
  * [ ] Looks
  * [ ] Sound
  * [ ] Events (including `broadcast _` & friends)
  * [ ] Control (including `stop _`)
  * [ ] Sensing (including `_ of _`)
  * [ ] Operators
  * [ ] Variables
  * [ ] My Blocks

**Comment by harbaum** [comment]
One of the most basic features for this is the support for translations. Currently these are in scratch-blocks/msg/messages.js and the translation system supposed to be there doesn't seem to be functional at all.

**Comment by cwillisf** [comment]
@harbaum we actually have a separate translation system for Scratch extensions. We're still figuring out the details but documentation on the current iteration is available here and will be updated as we progress:
https://github.com/LLK/scratch-vm/blob/develop/docs/extensions.md#translation

**Comment by harbaum** [comment]
Yes, i know. I tried to use it but it had no effect. I then searched the code and found no code that would care for these translations.

**Comment by apple502j** [comment]
@BryceLTaylor hm, adroitwhiz said "RIP extensionification" https://github.com/LLK/scratch-gui/issues/4400#issuecomment-627797933 - is it true?

**Comment by CommanderGL** [comment]
Will this finally be implemented because if not I'm putting it in my fork
