### ISSUE TITLE
Preserve project json metadata: `meta.origin`

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-vm#2851]
A project saved with an `origin` key in the `meta` section of the JSON should preserve the value when saved. Currently it's removed.

Don't create a default for this value. It should just be preserved if it's present.

(For CSFirst version of Scratch)

**Comment by apple502j** [comment]
Listing stuff
- [ ] runtime should hold the origin - perhaps `runtime.projectOrigin` ?
- [ ] runtime should clear it when it's disposed
- [ ] serialization/sb3.js should set the runtime attr and serialize the runtime attr
- [ ] add origin to scratch-parser

**Comment by kchadha** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Track "origin" field in project.json (to track Scratch for CSFirst projects that get uploaded to the Scratch Online Community)](https://trello.com/c/O1ddo5Um/199-track-origin-field-in-projectjson-to-track-scratch-for-csfirst-projects-that-get-uploaded-to-the-scratch-online-community)
