### ISSUE TITLE
Extension prototype checklist

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#606]
This is a checklist for work on the extensions prototype (the corresponding checklist for work in the GUI is [here](https://github.com/LLK/scratch-gui/issues/298)).

**Wedo**

- [x] "Set motor direction" should take effect while a motor is running (either due to the "motor on" or "motor on for secs" blocks)
- [x] Detect that the device manager has disconnected from the wedo (e.g. after the OS goes to sleep and wakes up) and try to reconnect
- [x] Refine [docs](https://github.com/LLK/internal-tools-scratch/wiki/How-to-use-the-SDM-with-a-different-server) for using Scratch Device Manager with the Wedo extension
- [x] Stop button should stop all motors
- [x] Monitors for distance and tilt reporters should be labeled correctly
- [x] Change "when tilted any" hat so it runs when any tilt axis changes from not tilted to tilted (currently it runs only when when all tilt axes are not tilted, and one axis changes to tilted)
- [x] "Tilted any?" Boolean reporter should work as before (after changing the behavior of "when tilted any?")

**Speech**

- [x] Speech recognition restarts fully on adding a new speech sprite (hopefully a workaround in the event of speech recognition silently crashing)
- [x] Stop button should stop speech synthesis utterances
- [x] Monitor for speech reporter should be labeled correctly
- [x] Multiple "when I hear" hats with the same input should all trigger (this requires either using the timeout workaround for edge-triggered hats, or changing this hat to be event-triggered)

**Bonus features**

- [ ] Try adding the Wedo block “When [distance, tilt] changes”

**Comment by TheBrokenRail** [comment]
Will extensions block code (or normal block code in general) be sandboxed so it can only access scratch related APIs and not be able to access XHTTP, document, etc? And if so will you be able to add your own extension to a scratch 3.0 project and publish it with that extension on the website, (not ScratchX)? And if you want to make more advanced extensions that are not sandboxed maybe only sandbox it on the official site?

**Comment by ericrosenbaum** [comment]
These are great questions. We are at an early stage with extensions for Scratch 3.0, so we don't know the answers yet- sorry!

**Comment by ericrosenbaum** [comment]
Closing this since we've completed the internal playtest
